### PR TITLE
Add custom headers to REFER from feature-server

### PR DESCRIPTION
**Pull request by Catharsis68**
This PR resolved an issue that the custom headers after a FS refer were not added

### CODE REVIEW

**Comment by davehorton** [comment]
@xquanluu can you test before this fix?  Because to my knowledge this feature is working on latest main branch and a fix should not be needed.  But I could be wrong so please test...

**Comment by xquanluu** [comment]
Yes, this is fixed in main branch

Refer verb:

```session
      .pause({length: 1.5})
      .say({
        text: 'Hello how are you'
      })
      .sip_refer({
        referTo: '+12345612341t2',
        actionHook: '/waithook',
        headers: {
          'custom1': 'hellow how are you'
        }
      })
      .send();```

Refer received at end client:

```REFER sip:rlgm81ul@6864mn4alc9g.invalid;transport=ws;ob SIP/2.0
Via: SIP/2.0/WSS 3.210.111.71:8443;branch=z9hG4bK1merp9HmjFt1D
Max-Forwards: 70
From: <sip:app-62844a92-9d01-482c-94ad-537afaf7ada5@sip.jambonz.me>;tag=c4BBDNKDrKSNa
To: "Hoan HL" <sip:xhoaluu@sip.jambonz.me>;tag=4faqcb509s
Call-ID: in56rake52jv667e4m8t
CSeq: 4911 REFER
Refer-To: <sip:+12345612341t2@14.226.233.31:59534>
Referred-By: <sip:xhoaluu@10.0.52.68>
Content-Length: 0
Custom1: hellow how are you
Contact: <sip:3.210.111.71:8443;transport=wss>
```

**Comment by Catharsis68** [comment]
@xquanluu  I think I missed that info: please test this way:  
1. create a call via API
2. within that called app - create a sip_refer with headers
3. check the PCAP

**Comment by xquanluu** [comment]
Thanks @Catharsis68 I'm able to reproduce.

Hi @davehorton 

The same code is using for sbc-inbound at https://github.com/jambonz/sbc-inbound/blob/main/lib/call-session.js#L931

And this code is missing for sbc-outbound, so I agreed this PR is valid

**Review by davehorton — APPROVED** [review]

**Pull request merged**
